---
framework: jest
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./tests/*.test.{js,ts}"
postMerge: 
  pattern: 
    - "./tests/*.test.{js,ts}"
postRun:
     command:
        - node --version
version: 1.1
